# NumPy Basics

### 1. Review를 위한 단계
- 방식 : 기존 실습 자료 및 검색을 하면서 이해하고 주석 달기
- 파일명 : **step03_Review이름.ipynb** 제출

In [171]:
import numpy as np

![Image of Yaktocat](https://image.slidesharecdn.com/numpypythoncheatsheet-181227141853/95/numpy-python-cheatsheet-1-638.jpg?cb=1545920343)

## The NumPy ndarray: A Multidimensional Array Object

#### <font color=#429bb8> Create 2x3 matrix </font>

np.random.randn(m,n): 평균0, 표준편차1의 가우시안 표준정규분포 난수를 matrix array(mxn) 생성

- np.random.randint 균일 분포의 정수 난수 1개 생성
- np.random.rand 0부터 1사이의 균일 분포에서 난수 matrix array생성
- np.random.randn 가우시안 표준 정규 분포에서 난수 matrix array 생성

https://nittaku.tistory.com/443


In [172]:
data = np.random.randn(2, 3)
data

array([[-1.13715885, -0.18601792,  0.56734848],
       [ 0.3232296 , -1.64641759, -0.58605071]])

In [173]:
data * 10 # 모든 수에 10을 곱하기 
data + data # 담긴 수 + 수

array([[-2.27431771, -0.37203585,  1.13469696],
       [ 0.6464592 , -3.29283518, -1.17210143]])

In [174]:
data.shape # (2,3) mxn matrix의 m,n 값 
data.dtype #dtype('float64')

dtype('float64')

### Creating ndarrays

In [175]:
# list를 numpy화 하는 과정 
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = int) #dtype 설정가능
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)
print(a)
print('---')
print(b)
print('---')
print(c)

[1 2 3]
---
[[1 2 3]
 [4 5 6]]
---
[[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]


In [176]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [177]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [178]:
arr2.ndim # 디멘션의 값 
arr2.shape # 행, 열

(2, 4)

In [179]:
arr1.dtype # 데이터의 타입 
arr2.dtype

dtype('int32')

In [180]:
np.zeros(10) # 0 값을 포함한 array 만들기
np.zeros((3, 6)) # 3x6 0값으로 채운 매트릭스 생성 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [181]:
np.arange(15) # 정렬 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

- a.shape: Array dimensions
- len(a): Length of array
- b.ndim: Number of array dimensions
- e.size: Number of array elements
- b.dtype: Data type of array elements
- b.dtype.name: Name of data type
- b.astype(int): Convert an array to a different type

In [182]:
arr1 = np.array([1, 2, 3], dtype=np.float64) # dtype 지정 
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype
arr2.dtype

dtype('int32')

In [183]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
# dtype 수정 
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [184]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [185]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype) #calibers 데이터 타입 복사해서 dtype 변경 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Arithmetic with NumPy Arrays

In [186]:
#array 에 연산 작업
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [187]:
1 / arr
arr ** 0.5 #=Root 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [188]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
#condition에 부합한것으로 array 생성하여 T/F 값을 넣기
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

In [189]:
arr = np.arange(10)
arr
arr[5] #6
arr[5:8] #6-8
arr[5:8] = 12 #6-8수정
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [190]:
arr_slice = arr[5:8] #6-8
arr_slice

array([12, 12, 12])

In [191]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [192]:
arr_slice[:] = 64 #전체값 
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [193]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2] #index 3값의 array 

array([7, 8, 9])

In [194]:
arr2d[0][2] #0행2열
arr2d[0, 2]

3

In [195]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) #3rd dimension 
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [196]:
print(arr3d)
print('====')
print(arr3d[0]) #two 2x1 array중 첫번째 출력 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
====
[[1 2 3]
 [4 5 6]]


- h = a.view() Create a view of the array with the same data
- np.copy(a) Create a copy of the array
- h = a.copy() Create a deep copy of the array

In [197]:
old_values = arr3d[0].copy()
arr3d[0] = 42 #42로 전체 변경
arr3d
# arr3d[0] = old_values
# arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [198]:
arr3d[1, 0]

array([7, 8, 9])

In [199]:
x = arr3d[1]
x
x[0]

array([7, 8, 9])

#### Indexing with slices

In [200]:
arr
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [201]:
print(arr2d)
print('---')
print(arr2d[:2]) # index 2 row를 제외한 그 전 값들 출력 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[[1 2 3]
 [4 5 6]]


In [202]:
arr2d[:2, 1:] 
# [:2, 1:]에서 :2가 [[1 0 0][4 0 0]] 1: 은 [[0 0][0 0]]

array([[2, 3],
       [5, 6]])

In [203]:
print(arr2d[1])
# print(arr2d[:2])
print(arr2d[1, :2])

[4 5 6]
[4 5]


In [204]:
arr2d[:2, 2]

array([3, 6])

In [205]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [206]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [207]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4) # 7x4 random 
names
data

array([[-0.89930108, -0.07899375, -2.55623576, -0.56220112],
       [ 0.12617728,  1.24532494,  0.67787362,  1.81505311],
       [ 0.49604404,  0.61650054, -0.65660798, -0.28917758],
       [-1.37198914,  0.87778883, -1.75253737,  1.93705294],
       [ 1.42324422, -0.33639346,  0.0915785 ,  1.1253986 ],
       [ 1.31543341, -0.34245022,  0.74006621, -1.81112107],
       [-0.96527572,  0.19551041, -1.65295749, -0.51115195]])

In [208]:
names == 'Bob' #if name == 'Bob', True or False

array([ True, False, False,  True, False, False, False])

In [209]:
data[names == 'Bob'] #Bob이라는 이름만 가진 값만 출력

array([[-0.89930108, -0.07899375, -2.55623576, -0.56220112],
       [-1.37198914,  0.87778883, -1.75253737,  1.93705294]])

In [210]:
print(data[names == 'Bob'])
print('-'*20)

# data행렬 1행, 4행에 해당하는 값중에서 3열,4열에 해당하는 값 추출
print(data[names == 'Bob', 2:])
print('-'*20)

# data행렬 1행 4행에 해당하는 값중에서 4열에 해당하는 값 추출
print(data[names == 'Bob', 3])

[[-0.89930108 -0.07899375 -2.55623576 -0.56220112]
 [-1.37198914  0.87778883 -1.75253737  1.93705294]]
--------------------
[[-2.55623576 -0.56220112]
 [-1.75253737  1.93705294]]
--------------------
[-0.56220112  1.93705294]


In [211]:
mask = (names == 'Bob') | (names == 'Will')
mask
data[mask]

array([[-0.89930108, -0.07899375, -2.55623576, -0.56220112],
       [ 0.49604404,  0.61650054, -0.65660798, -0.28917758],
       [-1.37198914,  0.87778883, -1.75253737,  1.93705294],
       [ 1.42324422, -0.33639346,  0.0915785 ,  1.1253986 ]])

In [212]:
data[data < 0] = 0 #0보다 작은 값들 0으로 수정
data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.12617728, 1.24532494, 0.67787362, 1.81505311],
       [0.49604404, 0.61650054, 0.        , 0.        ],
       [0.        , 0.87778883, 0.        , 1.93705294],
       [1.42324422, 0.        , 0.0915785 , 1.1253986 ],
       [1.31543341, 0.        , 0.74006621, 0.        ],
       [0.        , 0.19551041, 0.        , 0.        ]])

In [213]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.12617728, 1.24532494, 0.67787362, 1.81505311],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.31543341, 0.        , 0.74006621, 0.        ],
       [0.        , 0.19551041, 0.        , 0.        ]])

### Transposing Arrays and Swapping Axes

In [214]:
arr = np.arange(15).reshape((3, 5))
arr
arr.T # 3x5 -> 5x3 

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [215]:
arr = np.random.randn(6, 3)
arr
np.dot(arr.T, arr)

array([[ 3.89311225, -0.8400483 ,  0.33896956],
       [-0.8400483 ,  5.44102368,  1.94082263],
       [ 0.33896956,  1.94082263,  3.03502335]])

In [216]:
arr = np.arange(16).reshape((2, 2, 4)) # 3차원으로 변경 
arr
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [217]:
arr
arr.swapaxes(1, 2) #차원 축 바꾸기 (2x4 -> 4x2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## Universal Functions: Fast Element-Wise Array Functions

In [218]:
arr = np.arange(10)
arr
np.sqrt(arr) #squared root 

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [219]:
x = np.random.randn(8)
y = np.random.randn(8)
x
y
np.maximum(x, y) #max comparison 

array([ 1.90848432,  1.54589717, -0.06121331,  0.43256141, -0.20926881,
        0.99496551,  0.9858858 ,  0.26323057])

In [220]:
arr = np.random.randn(7) * 5
arr
remainder, whole_part = np.modf(arr) #int, float 분리 
remainder
whole_part

array([ 0., -2.,  0.,  3., -4.,  3.,  4.])

In [221]:
arr
np.sqrt(arr)
np.sqrt(arr, arr)
arr

<ipython-input-221-bcce5ef9aa78>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)
<ipython-input-221-bcce5ef9aa78>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr, arr)


array([0.20112109,        nan, 0.62622034, 1.82897396,        nan,
       1.76284908, 2.0995538 ])

### Expressing Conditional Logic as Array Operations

In [222]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [223]:
result = [(x if c else y) #c가 T면 x이고 F면 y
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [224]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [225]:
arr = np.random.randn(4, 4)
arr
arr > 0
np.where(arr > 0, 2, -2)

array([[-2,  2, -2, -2],
       [-2, -2,  2, -2],
       [ 2,  2, -2, -2],
       [ 2, -2, -2, -2]])

In [226]:
np.where(arr > 0, 2, arr) # set only positive values to 2

array([[-1.16114594,  2.        , -0.08793108, -1.98103931],
       [-0.45395523, -0.12187747,  2.        , -0.37216503],
       [ 2.        ,  2.        , -1.53197394, -0.42996111],
       [ 2.        , -0.88849748, -1.34883826, -1.23471427]])

### Mathematical and Statistical Methods

In [227]:
arr = np.random.randn(5, 4)
arr
arr.mean()
np.mean(arr)
arr.sum()

0.4137089277042665

- a.sort() Sort an array
- c.sort(axis=0) Sort the elements of an array's axis

In [228]:
arr.mean(axis=1) #axis 조건 걸기 
# axis = 1, working along the row, axis=0, working along the column 
arr.sum(axis=0)

array([-1.14151512,  2.36363446,  1.27222019, -2.08063061])

https://www.geeksforgeeks.org/numpy-mean-in-python/

In [229]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum() #cumulated sum 

array([ 0,  1,  3,  6, 10, 15, 21, 28], dtype=int32)

In [230]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr
arr.cumsum(axis=0)
arr.cumprod(axis=1) #cumulated product 

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]], dtype=int32)

### Methods for Boolean Arrays

In [231]:
arr = np.random.randn(100)
(arr > 0).sum() # Number of positive values

56

In [232]:
bools = np.array([False, False, True, False])
bools.any() #or
bools.all() #and

False

### Sorting

In [233]:
arr = np.random.randn(6)
arr
arr.sort() #정렬 ascending 
arr

array([-1.11465702, -0.14674685, -0.14538887, -0.03163277,  0.6433026 ,
        0.67603348])

In [234]:
arr = np.random.randn(5, 3)
arr
arr.sort(1) #1행 정렬 
arr

array([[-2.24043262, -0.66935827,  0.21919178],
       [-1.4718745 , -1.15951997, -0.60496849],
       [-1.60607782, -1.60371661, -1.05235165],
       [-0.9920415 , -0.52994532, -0.44867421],
       [-1.0024929 ,  0.06756631,  0.15788777]])

In [235]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))] # 5% quantile

-1.6795078485363424